.TH udm-kernel-boot 8 "March 2021" Linux "User Manuals"
.SH NAME
udm-kernel-boot \- boot into custom kernel
.SH SYNOPSIS
.B udm-kernel-boot
.IR kernel
.SH DESCRIPTION
.B udm-kernel-boot
uses the kexec functionality from the Linux kernel to boot into a custom kernel
image located at
.IR image .
.SH FILES
.TP
.I /usr/lib/udm-kernel-tools
Package files
.TP
.I /usr/share/doc/udm-kernel-tools
Documentation
