#!/bin/bash
# Bash script that is invoked when a kernel is installed and creates the initramfs.
# Based on initramfs-tools from Debian: https://salsa.debian.org/kernel-team/initramfs-tools
#
# Copyright (C) 2021 Debian authors.
# Copyright (C) 2021 Fabian Mastenbroek.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

version="$1"
bootdir=/boot

command -v udm-mkinitramfs >/dev/null 2>&1 || exit 0

# passing the kernel version is required
if [ -z "${version}" ]; then
	echo >&2 "W: $0: ${DPKG_MAINTSCRIPT_PACKAGE:-kernel package} did not pass a version number"
	exit 2
fi

# exit if kernel does not need an initramfs
if [ "$INITRD" = 'No' ]; then
	exit 0
fi

# absolute file name of kernel image may be passed as a second argument;
# create the initrd in the same directory
if [ -n "$2" ]; then
	bootdir=$(dirname "$2")
fi

# avoid running multiple times
if [ -n "$DEB_MAINT_PARAMS" ]; then
	eval set -- "$DEB_MAINT_PARAMS"
	if [ -z "$1" ] || [ "$1" != "configure" ]; then
		exit 0
	fi
fi

echo "udm-kernel-tools: Generating initramfs image for kernel $version"
udm-mkinitramfs -o "$bootdir"/initramfs-"$version".gz "$version" >&2
sync -f "$bootdir"/initramfs-"$version".gz
