#!/bin/sh
set -e
# Automatically added by dh_installsystemd/11.1.6ubuntu2
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'udm-autoboot.service' >/dev/null || true
fi
# End automatically added section
