name: Build

on: pull_request

jobs:
  build:
    runs-on: [ubuntu-20.04]
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v3
      with:
        path: udm-kernel-tools
        submodules: recursive
    - name: Setup Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install devscripts git gcc-aarch64-linux-gnu equivs
        sudo mk-build-deps --install udm-kernel-tools/debian/control
    - name: Build Package
      run: |
        cd udm-kernel-tools
        debuild -eGITHUB_TOKEN -uc -us -aarm64 --lintian-opts --profile debian
      env:
        GITHUB_TOKEN: ${{secrets.PAT}}
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        if-no-files-found: error
        path: |
          *.deb
          *.build*
          *.changes
          *.dsc
